services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  api1:
    build:
      context: ./java
    container_name: api1
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.8GB'

  api2:
    extends:
      service: api1
    container_name: api2