server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: rinha-java
    timezone: ${TIMEZONE:America/Sao_Paulo}
  datasource:
    url: jdbc:postgresql://${DB_HOST:java_db}:5432/${POSTGRES_DB:rinha}
    username: postgres
    password: postgres
  jmx:
    enabled: true
  jpa:
    open-in-view: true
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS